#!/usr/bin/python
import Adafruit_CharLCD as LCD
import Adafruit_DHT
import RPi.GPIO as gpio
import time
from datetime import datetime
import os

seq = 1    # init global sequence, today and time
today = ''
now = ''

def getDateTime():
    global today, now
    n = datetime.now()
    today = "   " + n.strftime('%d/%m/%Y') + "\n"
    now = "    " + n.strftime('%H:%M:%S')
    
try:
  print "Program will finish if you press CTRL+C\n"
  getDateTime()
  lcd.message(today)
  lcd.message(now)

while True:
    if seq == 1:
        getDateTime()
        lcd.set_cursor(0,1)
        lcd.message(now)
    time.sleep(1)
    print(seq)

finally:
  gpio.cleanup()
